### ISSUE TITLE
ページ構成の整理

### ISSUE THREAD

**Issue by shoma2da** [handshakejp/webui#39]
* トップ画面
* ログイン画面
* ユーザ登録画面
* ログイン後のトップ画面

を整理する。redirectなど。

**Comment by shoma2da** [comment]
![001](https://cloud.githubusercontent.com/assets/2342648/6164166/5c49602c-b2df-11e4-9e50-1595a5b4d2a2.jpg)

**Comment by shoma2da** [comment]
@himaratsu こんな感じにしようと思います。

**Comment by himaratsu** [comment]
![みさわ](http://jigokuno.img.jugem.jp/20110516_2116033.gif)

**Comment by himaratsu** [comment]
（http://hrysd.hatenablog.com/entry/2012/10/06/192648 より）
